name: fitnessgame_app
description: A new Flutter project.


version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_blue_plus: ^1.5.2
  flex_color_scheme: ^7.0.5
  google_fonts: ^4.0.4
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Medium.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
  uses-material-design: true